#pragma once

enum MY_DECISION {
    MY_BREAK,
    MY_CONTINUE
};

enum MY_MESSAGES {
    ERROR_MEM_ALLOC,
    ERROR_FILE_OPEN,
    ERROR_FILE_OUT_UNVALIABLE,
    ERROR_FILE_IN_UNVALIABLE,
    STACK_EMPTY,
    FILE_EMPTY,
    FILE_NOT_EXIST,
    NO_DATA_TO_PRINT,
    INVALID_DECISION,
    MY_MESSAGES_TOT
};

MY_DECISION messageFunction(MY_MESSAGES);
void criticalError(int);